import { resolve } from "node:path";
import { defineConfig } from "vite-plus";

export default defineConfig({
	resolve: {
		alias: {
			"@": resolve("src"),
		},
	},
	test: {
		clearMocks: true,
		coverage: {
			include: ["src"],
			reporter: ["html", "lcov"],
		},
		exclude: ["lib", "node_modules"],
		setupFiles: ["console-fail-test/setup"],
	},
	build: {
		lib: {
			entry: "src/index.ts",
			fileName: "index",
			formats: ["es"],
		},
		rollupOptions: {
			external: ["@typescript-eslint/utils"],
		},
	},
	pack: {
		dts: true,
		entry: [
			"src/index.ts",
			"src/utils.ts",
			"src/rules/index.ts",
			"src/rules/logger/require-logger-inline-attributes.ts",
			"src/rules/logger/require-logger-message.ts",
			"src/rules/logger/require-logger-primitive-attributes.ts",
			"src/rules/logger/require-logger-scoped-dot-notation.ts",
			"src/rules/logger/utils.ts",
		],
		fixedExtension: false,
		outDir: "lib",
		unbundle: true,
	},
	lint: {
		plugins: ["oxc", "typescript", "unicorn", "react"],
		categories: {
			correctness: "warn",
		},
		options: {
			typeAware: true,
			typeCheck: true,
		},
		env: {
			builtin: true,
		},
		ignorePatterns: [
			"**/*.snap",
			"**/coverage",
			"**/lib",
			"node_modules",
			"pnpm-lock.yaml",
		],
		overrides: [
			{
				files: ["**/*.{js,ts}"],
				rules: {
					"constructor-super": "error",
					"for-direction": "error",
					"getter-return": "error",
					"no-async-promise-executor": "error",
					"no-case-declarations": "error",
					"no-class-assign": "error",
					"no-compare-neg-zero": "error",
					"no-cond-assign": "error",
					"no-const-assign": "error",
					"no-constant-binary-expression": "error",
					"no-constant-condition": "error",
					"no-control-regex": "error",
					"no-debugger": "error",
					"no-delete-var": "error",
					"no-dupe-class-members": "error",
					"no-dupe-else-if": "error",
					"no-dupe-keys": "error",
					"no-duplicate-case": "error",
					"no-empty": "error",
					"no-empty-character-class": "error",
					"no-empty-pattern": "error",
					"no-empty-static-block": "error",
					"no-ex-assign": "error",
					"no-extra-boolean-cast": "error",
					"no-fallthrough": "error",
					"no-func-assign": "error",
					"no-global-assign": "error",
					"no-import-assign": "error",
					"no-invalid-regexp": "error",
					"no-irregular-whitespace": "error",
					"no-loss-of-precision": "error",
					"no-misleading-character-class": "error",
					"no-new-native-nonconstructor": "error",
					"no-nonoctal-decimal-escape": "error",
					"no-obj-calls": "error",
					"no-prototype-builtins": "error",
					"no-redeclare": "error",
					"no-regex-spaces": "error",
					"no-self-assign": "error",
					"no-setter-return": "error",
					"no-shadow-restricted-names": "error",
					"no-sparse-arrays": "error",
					"no-this-before-super": "error",
					"no-unassigned-vars": "error",
					"no-undef": "error",
					"no-unexpected-multiline": "error",
					"no-unreachable": "error",
					"no-unsafe-finally": "error",
					"no-unsafe-negation": "error",
					"no-unsafe-optional-chaining": "error",
					"no-unused-labels": "error",
					"no-unused-private-class-members": "error",
					"no-unused-vars": "error",
					"no-useless-assignment": "error",
					"no-useless-backreference": "error",
					"no-useless-catch": "error",
					"no-useless-escape": "error",
					"no-with": "error",
					"preserve-caught-error": "error",
					"require-yield": "error",
					"use-isnan": "error",
					"valid-typeof": "error",
					"no-array-constructor": "error",
					"no-implied-eval": "off",
					"no-unused-expressions": "error",
					"no-useless-constructor": "error",
					"no-throw-literal": "off",
					"prefer-promise-reject-errors": "off",
					"require-await": "off",
					"typescript/await-thenable": "error",
					"typescript/ban-ts-comment": [
						"error",
						{
							minimumDescriptionLength: 10,
						},
					],
					"typescript/no-array-delete": "error",
					"typescript/no-base-to-string": "error",
					"typescript/no-confusing-void-expression": "error",
					"typescript/no-deprecated": "error",
					"typescript/no-duplicate-enum-values": "error",
					"typescript/no-duplicate-type-constituents": "error",
					"typescript/no-dynamic-delete": "error",
					"typescript/no-empty-object-type": "error",
					"typescript/no-explicit-any": "error",
					"typescript/no-extra-non-null-assertion": "error",
					"typescript/no-extraneous-class": "error",
					"typescript/no-floating-promises": "error",
					"typescript/no-for-in-array": "error",
					"typescript/no-implied-eval": "error",
					"typescript/no-invalid-void-type": "error",
					"typescript/no-meaningless-void-operator": "error",
					"typescript/no-misused-new": "error",
					"typescript/no-misused-promises": "error",
					"typescript/no-misused-spread": "error",
					"typescript/no-mixed-enums": "error",
					"typescript/no-namespace": "error",
					"typescript/no-non-null-asserted-nullish-coalescing": "error",
					"typescript/no-non-null-asserted-optional-chain": "error",
					"typescript/no-non-null-assertion": "error",
					"typescript/no-redundant-type-constituents": "error",
					"typescript/no-require-imports": "error",
					"typescript/no-this-alias": "error",
					"typescript/no-unnecessary-boolean-literal-compare": "error",
					"typescript/no-unnecessary-condition": "error",
					"typescript/no-unnecessary-template-expression": "error",
					"typescript/no-unnecessary-type-arguments": "error",
					"typescript/no-unnecessary-type-assertion": "error",
					"typescript/no-unnecessary-type-constraint": "error",
					"typescript/no-unnecessary-type-conversion": "error",
					"typescript/no-unnecessary-type-parameters": "error",
					"typescript/no-unsafe-argument": "error",
					"typescript/no-unsafe-assignment": "error",
					"typescript/no-unsafe-call": "error",
					"typescript/no-unsafe-declaration-merging": "error",
					"typescript/no-unsafe-enum-comparison": "error",
					"typescript/no-unsafe-function-type": "error",
					"typescript/no-unsafe-member-access": "error",
					"typescript/no-unsafe-return": "error",
					"typescript/no-unsafe-unary-minus": "error",
					"typescript/no-useless-default-assignment": "error",
					"typescript/no-wrapper-object-types": "error",
					"typescript/only-throw-error": "error",
					"typescript/prefer-as-const": "error",
					"typescript/prefer-literal-enum-member": "error",
					"typescript/prefer-namespace-keyword": "error",
					"typescript/prefer-promise-reject-errors": "error",
					"typescript/prefer-reduce-type-parameter": "error",
					"typescript/prefer-return-this-type": "error",
					"typescript/related-getter-setter-pairs": "error",
					"typescript/require-await": "error",
					"typescript/restrict-plus-operands": [
						"error",
						{
							allowAny: false,
							allowBoolean: false,
							allowNullish: false,
							allowNumberAndString: false,
							allowRegExp: false,
						},
					],
					"typescript/restrict-template-expressions": [
						"error",
						{
							allowAny: false,
							allowBoolean: false,
							allowNever: false,
							allowNullish: false,
							allowNumber: false,
							allowRegExp: false,
						},
					],
					"typescript/return-await": [
						"error",
						"error-handling-correctness-only",
					],
					"typescript/triple-slash-reference": "error",
					"typescript/unbound-method": "error",
					"typescript/unified-signatures": "error",
					"typescript/use-unknown-in-catch-callback-variable": "error",
					"no-empty-function": "error",
					"typescript/adjacent-overload-signatures": "error",
					"typescript/array-type": "error",
					"typescript/ban-tslint-comment": "error",
					"typescript/class-literal-property-style": "error",
					"typescript/consistent-generic-constructors": "error",
					"typescript/consistent-indexed-object-style": "error",
					"typescript/consistent-type-assertions": "error",
					"typescript/consistent-type-definitions": "error",
					"typescript/dot-notation": "off",
					"typescript/no-confusing-non-null-assertion": "error",
					"typescript/no-inferrable-types": "error",
					"typescript/non-nullable-type-assertion-style": "error",
					"typescript/prefer-find": "error",
					"typescript/prefer-for-of": "error",
					"typescript/prefer-function-type": "error",
					"typescript/prefer-includes": "error",
					"typescript/prefer-nullish-coalescing": "error",
					"typescript/prefer-optional-chain": "error",
					"typescript/prefer-regexp-exec": "error",
					"typescript/prefer-string-starts-ends-with": "error",
				},
			},
			{
				files: ["src/**/*.ts"],
				rules: {
					"eslint-plugin/fixer-return": "error",
					"eslint-plugin/no-deprecated-context-methods": "error",
					"eslint-plugin/no-deprecated-report-api": "error",
					"eslint-plugin/no-identical-tests": "error",
					"eslint-plugin/no-meta-replaced-by": "error",
					"eslint-plugin/no-meta-schema-default": "error",
					"eslint-plugin/no-missing-message-ids": "error",
					"eslint-plugin/no-missing-placeholders": "error",
					"eslint-plugin/no-only-tests": "error",
					"eslint-plugin/no-unused-message-ids": "error",
					"eslint-plugin/no-unused-placeholders": "error",
					"eslint-plugin/no-useless-token-range": "error",
					"eslint-plugin/prefer-message-ids": "error",
					"eslint-plugin/prefer-object-rule": "error",
					"eslint-plugin/prefer-output-null": "error",
					"eslint-plugin/require-meta-default-options": "error",
					"eslint-plugin/require-meta-fixable": "error",
					"eslint-plugin/require-meta-has-suggestions": "error",
					"eslint-plugin/require-meta-schema-description": "error",
					"eslint-plugin/require-meta-schema": "error",
					"eslint-plugin/require-meta-type": "error",
				},
				jsPlugins: ["eslint-plugin-eslint-plugin"],
			},
			{
				files: ["**/*.test.*"],
				rules: {
					"vitest/expect-expect": "error",
					"vitest/no-commented-out-tests": "error",
					"vitest/no-conditional-expect": "error",
					"vitest/no-disabled-tests": "warn",
					"vitest/no-focused-tests": "error",
					"vitest/no-identical-title": "error",
					"vitest/no-import-node-test": "error",
					"vitest/no-interpolation-in-snapshots": "error",
					"vitest/no-mocks-import": "error",
					"vitest/no-standalone-expect": "error",
					"vitest/no-unneeded-async-expect-function": "error",
					"vitest/prefer-called-exactly-once-with": "error",
					"vitest/require-local-test-context-for-concurrent-snapshots": "error",
					"vitest/valid-describe-callback": "error",
					"vitest/valid-expect": "error",
					"vitest/valid-expect-in-promise": "error",
					"vitest/valid-title": "error",
					"typescript/no-unsafe-assignment": "off",
				},
				plugins: ["vitest"],
			},
		],
		jsPlugins: [
			{
				name: "vite-plus",
				specifier: "vite-plus/oxlint-plugin",
			},
		],
		rules: {
			"vite-plus/prefer-vite-plus-imports": "error",
		},
	},
	staged: {
		"*.{js,ts}": ["vp lint --fix --max-warnings 0", "vp fmt"],
		"*.{json,md,yml,yaml}": "vp fmt",
	},
	fmt: {
		useTabs: true,
		printWidth: 80,
		sortPackageJson: false,
		ignorePatterns: [
			".husky/",
			"node_modules/",
			".pnpm-store/",
			"lib/",
			"dist/",
			"coverage/",
			".vitest/",
			"*.log",
			"pnpm-debug.log*",
			".cache/",
			".parcel-cache/",
			".turbo/",
			".eslintcache",
			"*.tsbuildinfo",
			"pnpm-lock.yaml",
		],
	},
});
