description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: voidzero-dev/setup-vp@v1
      with:
        cache: true
        node-version: "24"
    - run: vp install --frozen-lockfile
      shell: bash
  using: composite
