jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/prepare
      - run: vp pack
      - run: node lib/index.js
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/prepare
      - run: vp pack
      - run: vp lint
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/prepare
      - run: vp fmt . --check
  knip:
    name: Knip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/prepare
      - run: vp run knip
  rule_docs:
    name: Rule Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/prepare
      - run: vp run docs:rules:check
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/prepare
      - run: vp test --coverage
      - if: always()
        uses: codecov/codecov-action@v7
  type_check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/prepare
      - run: vp run tsc

name: CI

on:
  pull_request: ~
  push:
    branches:
      - main
