jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/prepare
      - run: pnpm build
      - run: node lib/index.js
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/prepare
      - run: pnpm build
      - run: pnpm lint
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/prepare
      - run: pnpm format:check
  knip:
    name: Knip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/prepare
      - run: pnpm knip
  rule_docs:
    name: Rule Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/prepare
      - run: pnpm docs:rules:check
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/prepare
      - run: pnpm run test --coverage
      - if: always()
        uses: codecov/codecov-action@v6
  type_check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/prepare
      - run: pnpm tsc

name: CI

on:
  pull_request: ~
  push:
    branches:
      - main
